### PR TITLE
Add more new t2 instances

### PR DESCRIPTION
**Pull request by joelarmstrong**
This patch adds the [2 recently launched t2 instance types](https://aws.amazon.com/blogs/aws/new-t2-xlarge-and-t2-2xlarge-instances/), plus the t2.nano which was launched a while back.

### CODE REVIEW

**Comment by hschmidt** [comment]
+1

**Comment by cket** [comment]
jenkins, test this please

**Comment by cket** [comment]
Test failures are unrelated, jenkins, test this please.

**Comment by cket** [comment]
jenkins, test this please

**Comment by cket** [comment]
jenkins, test this please

**Comment by cket** [comment]
jenkins, test this please

**Pull request merged**
