### PR TITLE
Update to Spark 2.x and Hadoop 2.7.x

### LINKED ISSUE #235: Problem with Spark slaves connection
Spark slaves do not connect alone to the master after creation of the cluster.
I need to restart spark using the following command to make them connect

```
/opt/sparkbox/spark/sbin/stop-all.sh
/opt/sparkbox/spark/sbin/start-all.sh
```

I don't know if this is the problem but I update spark to version 2.0.1 and hadoop to version 2.7.3

### PR DESCRIPTION
**Pull request by hyviquel**
Submit update of Spark and Hadoop to try to fix #235 and #236 as suggested by @hannes-ucsc

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Ok, I see now what you did there. I think just changing the constants that specify the versions might not be sufficient. There are probably plenty other differences between these versions that need to be accounted for. That could explain #235 and #236.

**Comment by hyviquel** [comment]
_Plenty_ other differences might be exaggerated since Spark cluster instantiation works well except for the two issues I mentioned. It seems to me that this API for creating cluster stays quite stable across versions.
Anyway, I'll take a deeper look at cgcloud code to try to fix it. But first, I will update to java 8 (like #233) since I just noticed that spark 2.0 is dropping java 7 support.

**Comment by hannes-ucsc** [comment]
Be aware of #233.

Since we (UCSC and UCB) use Spark clusters internally with ADAM, we can't just ditch support for Spark 1.6.x right now. @fnothaft might want to chime in on this. IOW, we would need to make this user-selectable. Take a look at ToilBox and how it uses sub-classing to switch between Toil versions. With that approach the user would create an image with Spark 2.x by running

cgcloud create -IT spark2-box

while 

cgcloud create -IT spark-box

creates a Spark 1.x image. Once the image exists, the remainder of the CLI is the same between versions.

**Comment by fnothaft** [comment]
> Since we (UCSC and UCB) use Spark clusters internally with ADAM, we can't just ditch support for Spark 1.6.x right now.

ADAM supports Spark 2. We've tested much more extensively on Spark 1.6 than on Spark 2, but it would not be the end of the world to go to Spark 2.

That being said, I like your proposed approach @hannes-ucsc:

> Take a look at ToilBox and how it uses sub-classing to switch between Toil versions. With that approach the user would create an image with Spark 2.x by running
> 
> cgcloud create -IT spark2-box
> 
> while
> 
> cgcloud create -IT spark-box
> 
> creates a Spark 1.x image. Once the image exists, the remainder of the CLI is the same between versions.

**Comment by hannes-ucsc** [comment]
@hyviquel, I invited you to our GH org. Once you accept it, you can look at the test results in Jenkins. Interestingly, only one of the Spark tests failed (wordcount). The persistence test passed, which would support your concern that my use of _plenty_ is exaggerated ;-).

**Comment by hyviquel** [comment]
Thanks @hannes-ucsc, it's perfect. In fact, I was just asking you an access to your Jenkins 😉.
I agree with your _spark2-box_ approach, I'm also interested on switching from one version to another.

**Comment by hannes-ucsc** [comment]
The tests should exercise both versions of Spark. This could be done by making the current SparkClusterTests abstract and having two concrete subclasses. I can then look into running both concrete test cases in parallel.

**Comment by hyviquel** [comment]
@hannes-ucsc I cannot figure out how to fix the test execution with the abstract class architecture, any suggestion ?

**Comment by hyviquel** [comment]
Jenkins, test this please

**Comment by hannes-ucsc** [comment]
I'm not funded to work on `cgcloud` anymore, but I will try to keep maintaining it in my spare time. I need to figure out where to host continuous integration how to fund it.

**Pull request closed without merging**
