### PR TITLE
adds support for aws x1 instances.

### LINKED ISSUE #261: add support for aws x1 instances

### PR DESCRIPTION
**Pull request by ryanking**
I couldn't run the tests on this because they don't work on master for me either.

But this seems pretty straight forward.

resolves #261

### CODE REVIEW

**Comment by ejacox** [comment]
Thanks for this @ryanking. We are deprecating the cgcloud tools. Let us know if there is any functionality that should be migrated elsewhere.

**Comment by ryanking** [comment]
@ejacox the toil aws provisioner relies on cgcloud, which means I can't use x1 instances currently. Is there a workaround?

**Comment by ejacox** [comment]
It looks like we should move the code into the AWS provisioner. Or better yet, the instance types should not be hardcoded and put into a configuration file. I will create an issue for this.

**Comment by ryanking** [comment]
thanks @ejacox

**Pull request merged**
