### PR TITLE
Bump Spark version to 1.5.2.

### LINKED ISSUE #118: Bump Spark version to 1.5.2
Bump to Spark 1.5.2, which we are using for the ADAM/Toil recompute.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #118. Also, since Spark 1.5.2 has a binary build specific for Hadoop 2.6, I changed our link to pull that binary from the Apache mirror, as opposed to the Hadoop 2.4 binary.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Testing this now:

http://jenkins.cgcloud.info/job/cgcloud/244/

**Comment by hannes-ucsc** [comment]
Build 244 failed for unrelated reasons (hit resource limit). Branch will have to rebased to include the fix for showstopper #122.

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc; rebased on the fix for #122.

**Comment by hannes-ucsc** [comment]
For now head on over to #123 where I am testing these changes rebased on latest master with fixes for #122 and #121 merged in. If those tests succeed we can close this PR. Otherwise, we'll close #123 and continue here.

**Comment by hannes-ucsc** [comment]
Fixed minor issue with tests in #123 and merged that. Closing this one without merging.

**Comment by fnothaft** [comment]
SGTM; thanks @hannes-ucsc!

**Pull request closed without merging**
