### PR TITLE
Setup TOIL_WORKDIR on toil boxes (resolves #102)

### LINKED ISSUE #102: Add Toil Workdir as an environment variable on Toil boxes

### PR DESCRIPTION
**Pull request by arkal**
Resolves #102 
Environment variable TOIL_WORKDIR is set to /var/lib/toil and written to /etc/environment so it persists.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
I'm not sure /etc/environment is read by Upstart jobs. You'd have to prove to me that this works. If you can show that a Toil job can observe this variable, then by induction it must also be present in the worker and  the executor processes where it is actually used. A unite test would do it (there already are tests for Toil clusters where this would fit nicely), or at the very least a shell transcript.

If /etc/environment does not work for this, read my comments in #105.

**Comment by arkal** [comment]
I'm unsure of what exactly an upstart job is. Is it one that is run with the `exec` command? If so, Does this show what you want?

```
[centos@arjun-fake-podk ~]$ cat /etc/environment 
TOIL_WORKDIR=/data/test
[centos@arjun-fake-podk ~]$ env | grep TOIL
TOIL_WORKDIR=/data/test
[centos@arjun-fake-podk ~]$ echo 'echo $TOIL_WORKDIR' > test_upstart.sh
[centos@arjun-fake-podk ~]$ chmod 777 test_upstart.sh 
[centos@arjun-fake-podk ~]$ exec `pwd`/test_upstart.sh
/data/test
Connection to 128.114.61.151 closed.
Arjuns-MacBook-Pro:~ arjun$
```

**Comment by hannes-ucsc** [comment]
This just shoes that your login shell has it set. Tells us nothing about upstart or mesos-slave.

Upstart is Ubuntu's init system. Google "upstart ubuntu" to find out more. TOIL_WORKDIR needs to be set in the Toil worker process which is started by the Toil/Mesos executor, which is started by the mesos-slave, which is started by upstart. If upstart doesn't read /etc/environment, TOIL_WORKDIR won't be set in any of these processes. Toil jobs run in the worker process. If you can see observe TOIL_WORKDIR in a Toil job, you have shown that it is present in the worker and executor processes where it is used.

The most sustainable method of verifying that is as part of the tests in the cgcloud-toil distribution.

**Comment by hannes-ucsc** [comment]
Ideally, this should've been a single commit.

**Pull request merged**
